### ISSUE TITLE
Please comment here to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/devs-september#1]
Say anything ...

**Comment by ehanlon4** [comment]
anything

**Comment by yang1070** [comment]
add me

**Comment by mlambe56** [comment]
Comment

**Comment by beardofedu** [comment]
👋

**Comment by MichaelCrimando** [comment]
Add me pleaze

**Comment by eacarter** [comment]
anything

**Comment by vlad1456** [comment]
Please add me

**Comment by sandeepf184** [comment]
add me

**Comment by ecohen1** [comment]
hi

**Comment by tcarmean** [comment]
よろしくお願いします！

**Comment by Rconroy** [comment]
Commit.

**Comment by mblack88** [comment]
It's sunny out.

**Comment by jyh947** [comment]
Hello

**Comment by tayloead** [comment]
anything

**Comment by dorris1** [comment]
Hello

**Comment by githubteacher** [comment]
:tada: @ehanlon4, @yang1070, @mlambe56, @beardofedu, @MichaelCrimando, @eacarter, @vlad1456, @sandeepf184, @ecohen1, @tcarmean, @Rconroy, @mblack88, @jyh947, @tayloead, and @dorris1 are now  repository collaborators. :balloon:

**Comment by oleiford** [comment]
mmmm.....

**Comment by rampency** [comment]
awsome

**Comment by ghost** [comment]
This is what it looks like when i type.

**Comment by edavids2** [comment]
ok

**Comment by weiqsun** [comment]
to be added as collabrator

**Comment by githubteacher** [comment]
:tada: @oleiford, @rampency, @agoetzke, @edavids2, and @weiqsun are now  repository collaborators. :balloon:

**Comment by TuanBe** [comment]
Testing

**Comment by TuanBe** [comment]
I'm not a collaborator yet????

**Comment by tcarmean** [comment]
@githubteacher hi!

**Comment by KirkHansen747** [comment]
@githubteacher Hello

**Comment by githubteacher** [comment]
:tada: @TuanBe, @TuanBe, and @KirkHansen747 are now  repository collaborators. :balloon:

**Comment by ghost** [comment]
@Rconroy that's an awful comment

**Comment by weiqsun** [comment]
@weiqsun commented now

**Comment by tcarmean** [comment]
@githubteacher @beardofedu don't forget that nobody will be able to perform git (remote) operations on the CLI without first configuring git to use the proxy.
